# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrationPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationPage(QtWidgets.QWidget):
    def setupUi(self, CalibrationPage):
        CalibrationPage.setObjectName("CalibrationPage")
        CalibrationPage.resize(661, 561)
        CalibrationPage.setStyleSheet("background-color: rgb(35, 35, 38);")
        self.verticalLayout = QtWidgets.QVBoxLayout(CalibrationPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(CalibrationPage)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.Label_title = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_title.sizePolicy().hasHeightForWidth())
        self.Label_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Label_title.setFont(font)
        self.Label_title.setStyleSheet("color: white;")
        self.Label_title.setObjectName("Label_title")
        self.verticalLayout_14.addWidget(self.Label_title, 0, QtCore.Qt.AlignHCenter)
        self.image_label = QtWidgets.QLabel(self.frame_5)
        self.image_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.image_label.setFont(font)
        self.image_label.setAutoFillBackground(False)
        self.image_label.setStyleSheet("color: rgb(0, 255, 127)")
        self.image_label.setText("")
        self.image_label.setScaledContents(False)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setWordWrap(False)
        self.image_label.setObjectName("image_label")
        self.verticalLayout_14.addWidget(self.image_label)
        self.verticalLayout.addWidget(self.frame_5)

        self.retranslateUi(CalibrationPage)
        QtCore.QMetaObject.connectSlotsByName(CalibrationPage)

    def retranslateUi(self, CalibrationPage):
        _translate = QtCore.QCoreApplication.translate
        CalibrationPage.setWindowTitle(_translate("CalibrationPage", "Form"))
        self.Label_title.setText(_translate("CalibrationPage", "Calibration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CalibrationPage = QtWidgets.QWidget()
    ui = Ui_CalibrationPage()
    ui.setupUi(CalibrationPage)
    CalibrationPage.show()
    sys.exit(app.exec_())
