# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1209, 874)
        MainWindow.setStyleSheet("*\n"
"{\n"
"    background-color: rgb(35, 35, 38);\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: red;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(35, 35, 38);         /* Handle color */\n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/* Disable top and bottom arrows*/\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"\n"
"/*Slider*/\n"
"\n"
"\n"
"/*\n"
"QSlider::groove:horizontal { \n"
"    background-color: black;\n"
"    border: 0px solid; \n"
"    height: 5px; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: white; \n"
"    border: 2px solid; \n"
"    width: 10px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 7px; \n"
"}\n"
"*/\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: white;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #49BF88, stop: 1 #7289DA);\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"\n"
"/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.camMenu = QtWidgets.QWidget()
        self.camMenu.setObjectName("camMenu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.camMenu)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Splitter_frame = QtWidgets.QSplitter(self.camMenu)
        self.Splitter_frame.setOrientation(QtCore.Qt.Horizontal)
        self.Splitter_frame.setObjectName("Splitter_frame")
        self.cameraFrame = QtWidgets.QFrame(self.Splitter_frame)
        self.cameraFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrame.sizePolicy().hasHeightForWidth())
        self.cameraFrame.setSizePolicy(sizePolicy)
        self.cameraFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cameraFrame.setStyleSheet("")
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cameraFrame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.image_label = QtWidgets.QLabel(self.cameraFrame)
        self.image_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.image_label.setFont(font)
        self.image_label.setAutoFillBackground(False)
        self.image_label.setStyleSheet("color: rgb(0, 255, 127)")
        self.image_label.setScaledContents(False)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setWordWrap(False)
        self.image_label.setObjectName("image_label")
        self.verticalLayout.addWidget(self.image_label)
        self.Button_startCam = QtWidgets.QPushButton(self.cameraFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_startCam.sizePolicy().hasHeightForWidth())
        self.Button_startCam.setSizePolicy(sizePolicy)
        self.Button_startCam.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Button_startCam.setFont(font)
        self.Button_startCam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_startCam.setStyleSheet("")
        self.Button_startCam.setObjectName("Button_startCam")
        self.verticalLayout.addWidget(self.Button_startCam, 0, QtCore.Qt.AlignHCenter)
        self.sidePanel = QtWidgets.QFrame(self.Splitter_frame)
        self.sidePanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidePanel.sizePolicy().hasHeightForWidth())
        self.sidePanel.setSizePolicy(sizePolicy)
        self.sidePanel.setMinimumSize(QtCore.QSize(300, 0))
        self.sidePanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sidePanel.setStyleSheet("")
        self.sidePanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidePanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidePanel.setObjectName("sidePanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidePanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Splitter_sidePanel = QtWidgets.QSplitter(self.sidePanel)
        self.Splitter_sidePanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Splitter_sidePanel.sizePolicy().hasHeightForWidth())
        self.Splitter_sidePanel.setSizePolicy(sizePolicy)
        self.Splitter_sidePanel.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_sidePanel.setObjectName("Splitter_sidePanel")
        self.settingsFrame = QtWidgets.QFrame(self.Splitter_sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFrame.sizePolicy().hasHeightForWidth())
        self.settingsFrame.setSizePolicy(sizePolicy)
        self.settingsFrame.setStyleSheet("background-color:rgb(51, 55, 61); border-radius: 15px;")
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.settingsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.settingsFrame)
        self.line_2.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line_2.setStyleSheet("background-color: rgb(35, 35, 38)")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.scrollArea = QtWidgets.QScrollArea(self.settingsFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 468, 570))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: white;\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: -3 3px 0 3px;\n"
"}")
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(9, 20, -1, -1)
        self.verticalLayout_7.setSpacing(15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.formLayout_2 = QtWidgets.QFormLayout(self.frame_3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.Label_brightnessValue = QtWidgets.QLabel(self.frame_3)
        self.Label_brightnessValue.setStyleSheet("color: white;")
        self.Label_brightnessValue.setObjectName("Label_brightnessValue")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_brightnessValue)
        self.Slider_brightness = QtWidgets.QSlider(self.frame_3)
        self.Slider_brightness.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Slider_brightness.setStyleSheet("")
        self.Slider_brightness.setMinimum(-255)
        self.Slider_brightness.setMaximum(255)
        self.Slider_brightness.setPageStep(1)
        self.Slider_brightness.setProperty("value", 0)
        self.Slider_brightness.setSliderPosition(0)
        self.Slider_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_brightness.setInvertedAppearance(False)
        self.Slider_brightness.setInvertedControls(False)
        self.Slider_brightness.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_brightness.setTickInterval(1)
        self.Slider_brightness.setObjectName("Slider_brightness")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_brightness)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.verticalLayout_5.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setAutoFillBackground(False)
        self.groupBox_4.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: white;\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: -3 3px 0 3px;\n"
"}")
        self.groupBox_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_4.setFlat(False)
        self.groupBox_4.setCheckable(False)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_8.setContentsMargins(9, 20, -1, -1)
        self.verticalLayout_8.setSpacing(15)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.formLayout_3 = QtWidgets.QFormLayout(self.frame_4)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_contrastValue = QtWidgets.QLabel(self.frame_4)
        self.Label_contrastValue.setStyleSheet("color: white;")
        self.Label_contrastValue.setObjectName("Label_contrastValue")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_contrastValue)
        self.Slider_contrast = QtWidgets.QSlider(self.frame_4)
        self.Slider_contrast.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Slider_contrast.setStyleSheet("")
        self.Slider_contrast.setMinimum(0)
        self.Slider_contrast.setMaximum(100)
        self.Slider_contrast.setPageStep(1)
        self.Slider_contrast.setProperty("value", 10)
        self.Slider_contrast.setSliderPosition(10)
        self.Slider_contrast.setTracking(True)
        self.Slider_contrast.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_contrast.setInvertedAppearance(False)
        self.Slider_contrast.setInvertedControls(False)
        self.Slider_contrast.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.Slider_contrast.setTickInterval(1)
        self.Slider_contrast.setObjectName("Slider_contrast")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.Slider_contrast)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.verticalLayout_5.addWidget(self.groupBox_4)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: white;\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: -3 3px 0 3px;\n"
"}")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setContentsMargins(-1, 20, -1, -1)
        self.verticalLayout_11.setSpacing(15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_res_0 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_res_0.setStyleSheet("color: white;")
        self.radioButton_res_0.setObjectName("radioButton_res_0")
        self.verticalLayout_11.addWidget(self.radioButton_res_0)
        self.radioButton_res_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_res_1.setStyleSheet("color: white;")
        self.radioButton_res_1.setObjectName("radioButton_res_1")
        self.verticalLayout_11.addWidget(self.radioButton_res_1)
        self.radioButton_res_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_res_2.setStyleSheet("color:white;")
        self.radioButton_res_2.setChecked(True)
        self.radioButton_res_2.setObjectName("radioButton_res_2")
        self.verticalLayout_11.addWidget(self.radioButton_res_2)
        self.radioButton_res_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_res_3.setStyleSheet("color: white;")
        self.radioButton_res_3.setObjectName("radioButton_res_3")
        self.verticalLayout_11.addWidget(self.radioButton_res_3)
        self.radioButton_res_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_res_4.setStyleSheet("color:white;")
        self.radioButton_res_4.setObjectName("radioButton_res_4")
        self.verticalLayout_11.addWidget(self.radioButton_res_4)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet("\n"
"QGroupBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 9px;\n"
"    margin-top: 0.5em;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    color: white;\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: -3 3px 0 3px;\n"
"}")
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_6.setContentsMargins(9, 20, -1, -1)
        self.verticalLayout_6.setSpacing(15)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.radioButton_RGB = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_RGB.sizePolicy().hasHeightForWidth())
        self.radioButton_RGB.setSizePolicy(sizePolicy)
        self.radioButton_RGB.setStyleSheet("color:white;")
        self.radioButton_RGB.setChecked(True)
        self.radioButton_RGB.setObjectName("radioButton_RGB")
        self.verticalLayout_6.addWidget(self.radioButton_RGB)
        self.radioButton_Grayscale = QtWidgets.QRadioButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_Grayscale.sizePolicy().hasHeightForWidth())
        self.radioButton_Grayscale.setSizePolicy(sizePolicy)
        self.radioButton_Grayscale.setStyleSheet("color:white;")
        self.radioButton_Grayscale.setObjectName("radioButton_Grayscale")
        self.verticalLayout_6.addWidget(self.radioButton_Grayscale)
        self.radioButton_Edged = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_Edged.setStyleSheet("color:white;")
        self.radioButton_Edged.setObjectName("radioButton_Edged")
        self.verticalLayout_6.addWidget(self.radioButton_Edged)
        self.verticalLayout_5.addWidget(self.groupBox_2)
        self.Button_reset = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.Button_reset.setFont(font)
        self.Button_reset.setStyleSheet("/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}")
        self.Button_reset.setObjectName("Button_reset")
        self.verticalLayout_5.addWidget(self.Button_reset)
        self.verticalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.outputFrame = QtWidgets.QFrame(self.Splitter_sidePanel)
        self.outputFrame.setStyleSheet("background-color:rgb(51, 55, 61); border-radius: 15px;")
        self.outputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputFrame.setObjectName("outputFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.outputFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.outputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self.outputFrame)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background-color: rgb(35, 35, 38)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.outputFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Label_object = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_object.setFont(font)
        self.Label_object.setStyleSheet("color: white;")
        self.Label_object.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_object.setObjectName("Label_object")
        self.verticalLayout_10.addWidget(self.Label_object)
        self.verticalLayout_9.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.Splitter_sidePanel)
        self.horizontalLayout.addWidget(self.Splitter_frame)
        self.stackedWidget.addWidget(self.camMenu)
        self.startMenu = QtWidgets.QWidget()
        self.startMenu.setObjectName("startMenu")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.startMenu)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_5 = QtWidgets.QFrame(self.startMenu)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.Label_startMenuTitle = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Label_startMenuTitle.setFont(font)
        self.Label_startMenuTitle.setStyleSheet("color: white;")
        self.Label_startMenuTitle.setObjectName("Label_startMenuTitle")
        self.verticalLayout_13.addWidget(self.Label_startMenuTitle, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_12.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.startMenu)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1209, 22))
        self.menubar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0,0,0);")
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setAutoFillBackground(False)
        self.menuView.setStyleSheet("color: rgb(0,0,0);\n"
"selection-color: rgb(0,0,0);\n"
"selection-background-color: rgb(148, 212, 255);")
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setStyleSheet("color: rgb(0,0,0);\n"
"selection-color: rgb(0,0,0);\n"
"selection-background-color: rgb(148, 212, 255);")
        self.menuHelp.setObjectName("menuHelp")
        self.menuObject_detection = QtWidgets.QMenu(self.menubar)
        self.menuObject_detection.setObjectName("menuObject_detection")
        self.menuCalibrate = QtWidgets.QMenu(self.menubar)
        self.menuCalibrate.setObjectName("menuCalibrate")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.actionHow_to_use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.action_Camera = QtWidgets.QAction(MainWindow)
        self.action_Camera.setCheckable(True)
        self.action_Camera.setChecked(True)
        self.action_Camera.setObjectName("action_Camera")
        self.actionControls = QtWidgets.QAction(MainWindow)
        self.actionControls.setCheckable(True)
        self.actionControls.setChecked(True)
        self.actionControls.setObjectName("actionControls")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setCheckable(True)
        self.actionSettings.setChecked(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setCheckable(True)
        self.actionOutput.setChecked(True)
        self.actionOutput.setObjectName("actionOutput")
        self.actionSettings_2 = QtWidgets.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.actionOutput_2 = QtWidgets.QAction(MainWindow)
        self.actionOutput_2.setObjectName("actionOutput_2")
        self.action_SidePanel = QtWidgets.QAction(MainWindow)
        self.action_SidePanel.setCheckable(True)
        self.action_SidePanel.setChecked(True)
        self.action_SidePanel.setObjectName("action_SidePanel")
        self.actionFace_detection = QtWidgets.QAction(MainWindow)
        self.actionFace_detection.setObjectName("actionFace_detection")
        self.actionCar_detection = QtWidgets.QAction(MainWindow)
        self.actionCar_detection.setObjectName("actionCar_detection")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Output = QtWidgets.QAction(MainWindow)
        self.action_Output.setCheckable(True)
        self.action_Output.setChecked(True)
        self.action_Output.setObjectName("action_Output")
        self.menuView.addAction(self.action_Camera)
        self.menuView.addAction(self.action_SidePanel)
        self.menuView.addAction(self.action_Settings)
        self.menuView.addAction(self.action_Output)
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addSeparator()
        self.menuObject_detection.addAction(self.actionFace_detection)
        self.menuObject_detection.addAction(self.actionCar_detection)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuCalibrate.menuAction())
        self.menubar.addAction(self.menuObject_detection.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.image_label.setText(_translate("MainWindow", "PRESS \"Start\" TO START WEBCAM"))
        self.Button_startCam.setText(_translate("MainWindow", "Start"))
        self.label.setText(_translate("MainWindow", "Settings"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Brightness"))
        self.Label_brightnessValue.setText(_translate("MainWindow", "0"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Contrast"))
        self.Label_contrastValue.setText(_translate("MainWindow", "1"))
        self.groupBox.setTitle(_translate("MainWindow", "Resolution"))
        self.radioButton_res_0.setText(_translate("MainWindow", "160 x 120 (4:3) "))
        self.radioButton_res_1.setText(_translate("MainWindow", "320 x 240 (4:3)"))
        self.radioButton_res_2.setText(_translate("MainWindow", "640 x 480 (4:3)"))
        self.radioButton_res_3.setText(_translate("MainWindow", "800 x 600 (4:3) "))
        self.radioButton_res_4.setText(_translate("MainWindow", "1280 x 720 (16:9)"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Image"))
        self.radioButton_RGB.setText(_translate("MainWindow", "RGB"))
        self.radioButton_Grayscale.setText(_translate("MainWindow", "Grayscale"))
        self.radioButton_Edged.setText(_translate("MainWindow", "Edged"))
        self.Button_reset.setText(_translate("MainWindow", "Reset"))
        self.label_2.setText(_translate("MainWindow", "Output"))
        self.Label_object.setText(_translate("MainWindow", "Object"))
        self.Label_startMenuTitle.setText(_translate("MainWindow", "Calibration"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuObject_detection.setTitle(_translate("MainWindow", "Object detection"))
        self.menuCalibrate.setTitle(_translate("MainWindow", "Calibrate"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.actionHow_to_use.setText(_translate("MainWindow", "How to use"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.action_Camera.setText(_translate("MainWindow", "Camera"))
        self.actionControls.setText(_translate("MainWindow", "Controls"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionOutput.setText(_translate("MainWindow", "Output"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))
        self.actionOutput_2.setText(_translate("MainWindow", "Output"))
        self.action_SidePanel.setText(_translate("MainWindow", "Side panel"))
        self.actionFace_detection.setText(_translate("MainWindow", "Face detection"))
        self.actionCar_detection.setText(_translate("MainWindow", "Car detection"))
        self.action_Settings.setText(_translate("MainWindow", "Settings"))
        self.action_Output.setText(_translate("MainWindow", "Output"))


