# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainPage(object):
    def setupUi(self, MainPage):
        MainPage.setObjectName("MainPage")
        MainPage.resize(1238, 797)
        MainPage.setStyleSheet("*\n"
"{\n"
"    background-color: rgb(35, 35, 38);\n"
"    color:white;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: 0;\n"
"}\n"
"\n"
"/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}")
        self.horizontalLayout = QtWidgets.QHBoxLayout(MainPage)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Splitter_frame = QtWidgets.QSplitter(MainPage)
        self.Splitter_frame.setOrientation(QtCore.Qt.Horizontal)
        self.Splitter_frame.setObjectName("Splitter_frame")
        self.cameraFrame = QtWidgets.QFrame(self.Splitter_frame)
        self.cameraFrame.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFrame.sizePolicy().hasHeightForWidth())
        self.cameraFrame.setSizePolicy(sizePolicy)
        self.cameraFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.cameraFrame.setStyleSheet("border: none;")
        self.cameraFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.cameraFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.cameraFrame.setObjectName("cameraFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.cameraFrame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Splitter_cameraFrame = QtWidgets.QSplitter(self.cameraFrame)
        self.Splitter_cameraFrame.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_cameraFrame.setObjectName("Splitter_cameraFrame")
        self.frame_3 = QtWidgets.QFrame(self.Splitter_cameraFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.frame_3.setFont(font)
        self.frame_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.label_active_None = QtWidgets.QLabel(self.frame_3)
        self.label_active_None.setObjectName("label_active_None")
        self.horizontalLayout_3.addWidget(self.label_active_None)
        self.label_active_HC = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_active_HC.setFont(font)
        self.label_active_HC.setStyleSheet("color: #FF8B87;")
        self.label_active_HC.setObjectName("label_active_HC")
        self.horizontalLayout_3.addWidget(self.label_active_HC)
        self.label_active_YOLO = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_active_YOLO.setFont(font)
        self.label_active_YOLO.setStyleSheet("color: #7BE8BF;")
        self.label_active_YOLO.setObjectName("label_active_YOLO")
        self.horizontalLayout_3.addWidget(self.label_active_YOLO)
        self.label_active_CM = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_active_CM.setFont(font)
        self.label_active_CM.setStyleSheet("color: #95BDFF;")
        self.label_active_CM.setObjectName("label_active_CM")
        self.horizontalLayout_3.addWidget(self.label_active_CM)
        self.image_label = QtWidgets.QLabel(self.Splitter_cameraFrame)
        self.image_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_label.sizePolicy().hasHeightForWidth())
        self.image_label.setSizePolicy(sizePolicy)
        self.image_label.setMinimumSize(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.image_label.setFont(font)
        self.image_label.setAutoFillBackground(False)
        self.image_label.setStyleSheet("color: rgb(0, 255, 127)")
        self.image_label.setScaledContents(False)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setWordWrap(False)
        self.image_label.setObjectName("image_label")
        self.frame_4 = QtWidgets.QFrame(self.Splitter_cameraFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 39))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Button_startCam = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_startCam.sizePolicy().hasHeightForWidth())
        self.Button_startCam.setSizePolicy(sizePolicy)
        self.Button_startCam.setMinimumSize(QtCore.QSize(100, 30))
        self.Button_startCam.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Button_startCam.setFont(font)
        self.Button_startCam.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Button_startCam.setStyleSheet("color:black;")
        self.Button_startCam.setObjectName("Button_startCam")
        self.horizontalLayout_2.addWidget(self.Button_startCam)
        self.verticalLayout.addWidget(self.Splitter_cameraFrame)
        self.sidePanel = QtWidgets.QFrame(self.Splitter_frame)
        self.sidePanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sidePanel.sizePolicy().hasHeightForWidth())
        self.sidePanel.setSizePolicy(sizePolicy)
        self.sidePanel.setMinimumSize(QtCore.QSize(0, 0))
        self.sidePanel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.sidePanel.setStyleSheet("border: none;")
        self.sidePanel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.sidePanel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.sidePanel.setObjectName("sidePanel")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidePanel)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Splitter_sidePanel = QtWidgets.QSplitter(self.sidePanel)
        self.Splitter_sidePanel.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Splitter_sidePanel.sizePolicy().hasHeightForWidth())
        self.Splitter_sidePanel.setSizePolicy(sizePolicy)
        self.Splitter_sidePanel.setStyleSheet("")
        self.Splitter_sidePanel.setLineWidth(1)
        self.Splitter_sidePanel.setOrientation(QtCore.Qt.Vertical)
        self.Splitter_sidePanel.setHandleWidth(5)
        self.Splitter_sidePanel.setObjectName("Splitter_sidePanel")
        self.settingsFrame = QtWidgets.QFrame(self.Splitter_sidePanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsFrame.sizePolicy().hasHeightForWidth())
        self.settingsFrame.setSizePolicy(sizePolicy)
        self.settingsFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.settingsFrame.setAutoFillBackground(False)
        self.settingsFrame.setStyleSheet("QTabWidget::pane {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color:transparent; \n"
"    border-radius:10;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    font-size:9pt;\n"
"    height: 35px;\n"
"    width: 140px;\n"
"    background-color: rgb(61, 65, 71);\n"
"    color: white;\n"
"    padding: 0px;\n"
"    border-top-left-radius: 6px;\n"
"    border-top-right-radius: 6px;\n"
"    margin-right:5px;\n"
"\n"
"}\n"
"\n"
"QTabBar::tab:!selected{\n"
"    background-color: rgb(41, 45, 51);\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"\n"
"")
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setLineWidth(1)
        self.settingsFrame.setObjectName("settingsFrame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.settingsFrame)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.settingsFrame)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_GeneralSettings = QtWidgets.QWidget()
        self.tab_GeneralSettings.setAutoFillBackground(False)
        self.tab_GeneralSettings.setObjectName("tab_GeneralSettings")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab_GeneralSettings)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_9 = QtWidgets.QFrame(self.tab_GeneralSettings)
        self.frame_9.setAutoFillBackground(False)
        self.frame_9.setStyleSheet("*{\n"
"    background-color: rgb(61, 65, 71);\n"
"    color: white;\n"
"}\n"
"QFrame{\n"
"    border-radius:10;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: gray;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(35, 35, 38);         /* Handle color */\n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/* Disable top and bottom arrows*/\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    background: white;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #49BF88, stop: 1 #7289DA);\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color: #2F3136;\n"
"    color: white;\n"
"    border-radius:0;\n"
"    padding:5px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid;\n"
"    border-color: transparent;\n"
"    background-color: transparent;\n"
"    border-radius:10;\n"
"    padding-top:15px; \n"
"    margin-top:-15px\n"
"}\n"
"\n"
"QRadioButton::indicator\n"
"{\n"
"    width : 20px;\n"
"    height : 20px;\n"
"}\n"
"\n"
"QFrame{\n"
"    border-top-left-radius:0;\n"
"    border-top-right-radius:0;\n"
"}\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_3.setContentsMargins(0, 25, 0, 9)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setAutoFillBackground(False)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 569, 568))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setStyleSheet("")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(15)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_13.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_13.setSpacing(15)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.radioButton_showFrameRate = QtWidgets.QRadioButton(self.groupBox_5)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        font.setKerning(False)
        self.radioButton_showFrameRate.setFont(font)
        self.radioButton_showFrameRate.setStyleSheet("")
        self.radioButton_showFrameRate.setIconSize(QtCore.QSize(16, 16))
        self.radioButton_showFrameRate.setObjectName("radioButton_showFrameRate")
        self.verticalLayout_13.addWidget(self.radioButton_showFrameRate)
        self.verticalLayout_5.addWidget(self.groupBox_5)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.groupBox = QtWidgets.QGroupBox(self.frame_2)
        self.groupBox.setStyleSheet("")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_11.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_11.setSpacing(15)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.radioButton_res_0 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.radioButton_res_0.setFont(font)
        self.radioButton_res_0.setStyleSheet("")
        self.radioButton_res_0.setObjectName("radioButton_res_0")
        self.verticalLayout_11.addWidget(self.radioButton_res_0)
        self.radioButton_res_1 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.radioButton_res_1.setFont(font)
        self.radioButton_res_1.setStyleSheet("")
        self.radioButton_res_1.setObjectName("radioButton_res_1")
        self.verticalLayout_11.addWidget(self.radioButton_res_1)
        self.radioButton_res_2 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.radioButton_res_2.setFont(font)
        self.radioButton_res_2.setStyleSheet("")
        self.radioButton_res_2.setChecked(True)
        self.radioButton_res_2.setObjectName("radioButton_res_2")
        self.verticalLayout_11.addWidget(self.radioButton_res_2)
        self.radioButton_res_3 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.radioButton_res_3.setFont(font)
        self.radioButton_res_3.setStyleSheet("")
        self.radioButton_res_3.setObjectName("radioButton_res_3")
        self.verticalLayout_11.addWidget(self.radioButton_res_3)
        self.radioButton_res_4 = QtWidgets.QRadioButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(8)
        self.radioButton_res_4.setFont(font)
        self.radioButton_res_4.setStyleSheet("")
        self.radioButton_res_4.setObjectName("radioButton_res_4")
        self.verticalLayout_11.addWidget(self.radioButton_res_4)
        self.verticalLayout_5.addWidget(self.groupBox)
        self.verticalLayout_4.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_16.addWidget(self.frame_9)
        self.tabWidget.addTab(self.tab_GeneralSettings, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.tab_6)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_10 = QtWidgets.QFrame(self.tab_6)
        self.frame_10.setAutoFillBackground(False)
        self.frame_10.setStyleSheet("*{\n"
"    background-color: rgb(61, 65, 71);\n"
"    color: white;\n"
"}\n"
"\n"
"QFrame{\n"
"    border-top-left-radius:0;\n"
"    border-top-right-radius:0;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: gray;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(35, 35, 38);         /* Handle color */\n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/* Disable top and bottom arrows*/\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 9)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea_2.setAutoFillBackground(False)
        self.scrollArea_2.setStyleSheet("")
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 569, 593))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setStyleSheet("")
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(25)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_11.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(10)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.toolBox = QtWidgets.QToolBox(self.scrollAreaWidgetContents_2)
        self.toolBox.setStyleSheet("*{\n"
"    background-color: rgb(61, 65, 71);\n"
"    color: white;\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    background-color: #2F3136;\n"
"    color: white;\n"
"    border-radius:0;\n"
"    padding:5px;\n"
"}\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: gray;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(35, 35, 38);         /* Handle color */\n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/* Disable top and bottom arrows*/\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    background: white;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #49BF88, stop: 1 #7289DA);\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 2px solid;\n"
"    border-color: #2F3136;\n"
"    margin-top: 27px;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QGroupBox:title{\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top center;\n"
"    padding: 6 10 6 10;\n"
"    background-color: #2F3136;\n"
"    border-top-left-radius: 10;\n"
"    border-top-right-radius: 10;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: transparent;\n"
"    border-top-left-radius:0;\n"
"    border-top-right-radius:0;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 569, 676))
        self.page.setObjectName("page")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_21.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_21.setSpacing(10)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.groupBox_HC_Cars = QtWidgets.QGroupBox(self.page)
        self.groupBox_HC_Cars.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_HC_Cars.setFont(font)
        self.groupBox_HC_Cars.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_HC_Cars.setObjectName("groupBox_HC_Cars")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.groupBox_HC_Cars)
        self.verticalLayout_25.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_25.setSpacing(40)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_HC_Cars)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(15)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_14 = QtWidgets.QFrame(self.frame_5)
        self.frame_14.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.formLayout_8 = QtWidgets.QFormLayout(self.frame_14)
        self.formLayout_8.setContentsMargins(0, 0, 0, 0)
        self.formLayout_8.setSpacing(10)
        self.formLayout_8.setObjectName("formLayout_8")
        self.horizontalSlider_HC_Cars_ScaleFactor = QtWidgets.QSlider(self.frame_14)
        self.horizontalSlider_HC_Cars_ScaleFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_Cars_ScaleFactor.setMinimum(105)
        self.horizontalSlider_HC_Cars_ScaleFactor.setMaximum(400)
        self.horizontalSlider_HC_Cars_ScaleFactor.setSingleStep(5)
        self.horizontalSlider_HC_Cars_ScaleFactor.setPageStep(5)
        self.horizontalSlider_HC_Cars_ScaleFactor.setProperty("value", 105)
        self.horizontalSlider_HC_Cars_ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_Cars_ScaleFactor.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_HC_Cars_ScaleFactor.setObjectName("horizontalSlider_HC_Cars_ScaleFactor")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_Cars_ScaleFactor)
        self.label_HC_Cars_ScaleFactor = QtWidgets.QLabel(self.frame_14)
        self.label_HC_Cars_ScaleFactor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_Cars_ScaleFactor.setStyleSheet("")
        self.label_HC_Cars_ScaleFactor.setObjectName("label_HC_Cars_ScaleFactor")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_HC_Cars_ScaleFactor)
        self.label_10 = QtWidgets.QLabel(self.frame_14)
        self.label_10.setStyleSheet("")
        self.label_10.setObjectName("label_10")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_10)
        self.verticalLayout_22.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_5)
        self.frame_15.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.formLayout_9 = QtWidgets.QFormLayout(self.frame_15)
        self.formLayout_9.setContentsMargins(0, 0, 0, 0)
        self.formLayout_9.setSpacing(10)
        self.formLayout_9.setObjectName("formLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_15)
        self.label_11.setStyleSheet("")
        self.label_11.setObjectName("label_11")
        self.formLayout_9.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.label_HC_Cars_MinNeighbors = QtWidgets.QLabel(self.frame_15)
        self.label_HC_Cars_MinNeighbors.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_Cars_MinNeighbors.setStyleSheet("")
        self.label_HC_Cars_MinNeighbors.setObjectName("label_HC_Cars_MinNeighbors")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_HC_Cars_MinNeighbors)
        self.horizontalSlider_HC_Cars_MinNeighbors = QtWidgets.QSlider(self.frame_15)
        self.horizontalSlider_HC_Cars_MinNeighbors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_Cars_MinNeighbors.setMaximum(100)
        self.horizontalSlider_HC_Cars_MinNeighbors.setProperty("value", 5)
        self.horizontalSlider_HC_Cars_MinNeighbors.setSliderPosition(5)
        self.horizontalSlider_HC_Cars_MinNeighbors.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_Cars_MinNeighbors.setObjectName("horizontalSlider_HC_Cars_MinNeighbors")
        self.formLayout_9.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_Cars_MinNeighbors)
        self.verticalLayout_22.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_5)
        self.frame_16.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.formLayout_10 = QtWidgets.QFormLayout(self.frame_16)
        self.formLayout_10.setContentsMargins(0, 0, 0, 0)
        self.formLayout_10.setSpacing(10)
        self.formLayout_10.setObjectName("formLayout_10")
        self.horizontalSlider_HC_Cars_MinSize = QtWidgets.QSlider(self.frame_16)
        self.horizontalSlider_HC_Cars_MinSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_Cars_MinSize.setMinimum(0)
        self.horizontalSlider_HC_Cars_MinSize.setMaximum(400)
        self.horizontalSlider_HC_Cars_MinSize.setSingleStep(10)
        self.horizontalSlider_HC_Cars_MinSize.setPageStep(10)
        self.horizontalSlider_HC_Cars_MinSize.setProperty("value", 0)
        self.horizontalSlider_HC_Cars_MinSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_Cars_MinSize.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_HC_Cars_MinSize.setObjectName("horizontalSlider_HC_Cars_MinSize")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_Cars_MinSize)
        self.label_HC_Cars_MinSize = QtWidgets.QLabel(self.frame_16)
        self.label_HC_Cars_MinSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_Cars_MinSize.setStyleSheet("")
        self.label_HC_Cars_MinSize.setObjectName("label_HC_Cars_MinSize")
        self.formLayout_10.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_HC_Cars_MinSize)
        self.label_12 = QtWidgets.QLabel(self.frame_16)
        self.label_12.setStyleSheet("")
        self.label_12.setObjectName("label_12")
        self.formLayout_10.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_12)
        self.verticalLayout_22.addWidget(self.frame_16)
        self.Button_HC_Cars_Reset = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.Button_HC_Cars_Reset.setFont(font)
        self.Button_HC_Cars_Reset.setStyleSheet("/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}")
        self.Button_HC_Cars_Reset.setObjectName("Button_HC_Cars_Reset")
        self.verticalLayout_22.addWidget(self.Button_HC_Cars_Reset)
        self.verticalLayout_25.addWidget(self.frame_5)
        self.groupBox_HC_LicencePlates = QtWidgets.QGroupBox(self.groupBox_HC_Cars)
        self.groupBox_HC_LicencePlates.setCheckable(True)
        self.groupBox_HC_LicencePlates.setChecked(False)
        self.groupBox_HC_LicencePlates.setObjectName("groupBox_HC_LicencePlates")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_HC_LicencePlates)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_17 = QtWidgets.QFrame(self.groupBox_HC_LicencePlates)
        self.frame_17.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.formLayout_11 = QtWidgets.QFormLayout(self.frame_17)
        self.formLayout_11.setObjectName("formLayout_11")
        self.horizontalSlider_HC_LicencePlates_ScaleFactor = QtWidgets.QSlider(self.frame_17)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setMinimum(105)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setMaximum(400)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setSingleStep(5)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setPageStep(5)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setProperty("value", 105)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_HC_LicencePlates_ScaleFactor.setObjectName("horizontalSlider_HC_LicencePlates_ScaleFactor")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_LicencePlates_ScaleFactor)
        self.label_HC_LicencePlates_ScaleFactor = QtWidgets.QLabel(self.frame_17)
        self.label_HC_LicencePlates_ScaleFactor.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_LicencePlates_ScaleFactor.setStyleSheet("")
        self.label_HC_LicencePlates_ScaleFactor.setObjectName("label_HC_LicencePlates_ScaleFactor")
        self.formLayout_11.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_HC_LicencePlates_ScaleFactor)
        self.label_13 = QtWidgets.QLabel(self.frame_17)
        self.label_13.setStyleSheet("")
        self.label_13.setObjectName("label_13")
        self.formLayout_11.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_13)
        self.verticalLayout_14.addWidget(self.frame_17)
        self.frame_18 = QtWidgets.QFrame(self.groupBox_HC_LicencePlates)
        self.frame_18.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.formLayout_12 = QtWidgets.QFormLayout(self.frame_18)
        self.formLayout_12.setObjectName("formLayout_12")
        self.label_14 = QtWidgets.QLabel(self.frame_18)
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        self.formLayout_12.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_14)
        self.label_HC_LicencePlates_MinNeighbors = QtWidgets.QLabel(self.frame_18)
        self.label_HC_LicencePlates_MinNeighbors.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_LicencePlates_MinNeighbors.setStyleSheet("")
        self.label_HC_LicencePlates_MinNeighbors.setObjectName("label_HC_LicencePlates_MinNeighbors")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_HC_LicencePlates_MinNeighbors)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors = QtWidgets.QSlider(self.frame_18)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setMaximum(100)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setProperty("value", 5)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setSliderPosition(5)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_LicencePlates_MinNeighbors.setObjectName("horizontalSlider_HC_LicencePlates_MinNeighbors")
        self.formLayout_12.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_LicencePlates_MinNeighbors)
        self.verticalLayout_14.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.groupBox_HC_LicencePlates)
        self.frame_19.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.formLayout_13 = QtWidgets.QFormLayout(self.frame_19)
        self.formLayout_13.setObjectName("formLayout_13")
        self.horizontalSlider_HC_LicencePlates_MinSize = QtWidgets.QSlider(self.frame_19)
        self.horizontalSlider_HC_LicencePlates_MinSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_HC_LicencePlates_MinSize.setMinimum(0)
        self.horizontalSlider_HC_LicencePlates_MinSize.setMaximum(400)
        self.horizontalSlider_HC_LicencePlates_MinSize.setSingleStep(10)
        self.horizontalSlider_HC_LicencePlates_MinSize.setPageStep(10)
        self.horizontalSlider_HC_LicencePlates_MinSize.setProperty("value", 0)
        self.horizontalSlider_HC_LicencePlates_MinSize.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_HC_LicencePlates_MinSize.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_HC_LicencePlates_MinSize.setObjectName("horizontalSlider_HC_LicencePlates_MinSize")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_HC_LicencePlates_MinSize)
        self.label_HC_LicencePlates_MinSize = QtWidgets.QLabel(self.frame_19)
        self.label_HC_LicencePlates_MinSize.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_HC_LicencePlates_MinSize.setStyleSheet("")
        self.label_HC_LicencePlates_MinSize.setObjectName("label_HC_LicencePlates_MinSize")
        self.formLayout_13.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_HC_LicencePlates_MinSize)
        self.label_15 = QtWidgets.QLabel(self.frame_19)
        self.label_15.setStyleSheet("")
        self.label_15.setObjectName("label_15")
        self.formLayout_13.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_15)
        self.verticalLayout_14.addWidget(self.frame_19)
        self.Button_HC_LicencePlates_Reset = QtWidgets.QPushButton(self.groupBox_HC_LicencePlates)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.Button_HC_LicencePlates_Reset.setFont(font)
        self.Button_HC_LicencePlates_Reset.setStyleSheet("/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}")
        self.Button_HC_LicencePlates_Reset.setObjectName("Button_HC_LicencePlates_Reset")
        self.verticalLayout_14.addWidget(self.Button_HC_LicencePlates_Reset)
        self.verticalLayout_25.addWidget(self.groupBox_HC_LicencePlates)
        self.verticalLayout_21.addWidget(self.groupBox_HC_Cars, 0, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 569, 484))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.groupBox_HC_Cars_3 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_HC_Cars_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.groupBox_HC_Cars_3.setFont(font)
        self.groupBox_HC_Cars_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox_HC_Cars_3.setTitle("")
        self.groupBox_HC_Cars_3.setObjectName("groupBox_HC_Cars_3")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.groupBox_HC_Cars_3)
        self.verticalLayout_27.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_27.setSpacing(40)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_HC_Cars_3)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(15)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_27 = QtWidgets.QFrame(self.frame_7)
        self.frame_27.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.formLayout_21 = QtWidgets.QFormLayout(self.frame_27)
        self.formLayout_21.setContentsMargins(0, 0, 0, 0)
        self.formLayout_21.setSpacing(10)
        self.formLayout_21.setObjectName("formLayout_21")
        self.label_23 = QtWidgets.QLabel(self.frame_27)
        self.label_23.setStyleSheet("")
        self.label_23.setObjectName("label_23")
        self.formLayout_21.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_23)
        self.label_YOLO_Treshold = QtWidgets.QLabel(self.frame_27)
        self.label_YOLO_Treshold.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_YOLO_Treshold.setStyleSheet("")
        self.label_YOLO_Treshold.setObjectName("label_YOLO_Treshold")
        self.formLayout_21.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_YOLO_Treshold)
        self.horizontalSlider_YOLO_Treshold = QtWidgets.QSlider(self.frame_27)
        self.horizontalSlider_YOLO_Treshold.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.horizontalSlider_YOLO_Treshold.setMaximum(100)
        self.horizontalSlider_YOLO_Treshold.setPageStep(1)
        self.horizontalSlider_YOLO_Treshold.setProperty("value", 50)
        self.horizontalSlider_YOLO_Treshold.setSliderPosition(50)
        self.horizontalSlider_YOLO_Treshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_YOLO_Treshold.setObjectName("horizontalSlider_YOLO_Treshold")
        self.formLayout_21.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.horizontalSlider_YOLO_Treshold)
        self.verticalLayout_28.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_7)
        self.frame_28.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.formLayout_22 = QtWidgets.QFormLayout(self.frame_28)
        self.formLayout_22.setContentsMargins(0, 0, 0, 0)
        self.formLayout_22.setSpacing(10)
        self.formLayout_22.setObjectName("formLayout_22")
        self.verticalLayout_28.addWidget(self.frame_28)
        self.Button_YOLO_Reset = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(12)
        self.Button_YOLO_Reset.setFont(font)
        self.Button_YOLO_Reset.setStyleSheet("/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}")
        self.Button_YOLO_Reset.setObjectName("Button_YOLO_Reset")
        self.verticalLayout_28.addWidget(self.Button_YOLO_Reset)
        self.verticalLayout_27.addWidget(self.frame_7)
        self.verticalLayout_6.addWidget(self.groupBox_HC_Cars_3, 0, QtCore.Qt.AlignTop)
        self.toolBox.addItem(self.page_2, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 569, 676))
        self.page_4.setObjectName("page_4")
        self.toolBox.addItem(self.page_4, "")
        self.verticalLayout_18.addWidget(self.toolBox)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_17.addWidget(self.scrollArea_2)
        self.verticalLayout_20.addWidget(self.frame_10)
        self.tabWidget.addTab(self.tab_6, "")
        self.verticalLayout_12.addWidget(self.tabWidget)
        self.outputFrame = QtWidgets.QFrame(self.Splitter_sidePanel)
        self.outputFrame.setStyleSheet("background-color: rgb(61, 65, 71);\n"
"border-top-left-radius: 10;\n"
"border-top-right-radius: 10;\n"
"border-bottom-left-radius: 10;")
        self.outputFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.outputFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.outputFrame.setObjectName("outputFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.outputFrame)
        self.verticalLayout_9.setContentsMargins(-1, 9, -1, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.outputFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.line = QtWidgets.QFrame(self.outputFrame)
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background-color: rgb(35, 35, 38);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.frame = QtWidgets.QFrame(self.outputFrame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.Label_object = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Label_object.setFont(font)
        self.Label_object.setStyleSheet("color: white;")
        self.Label_object.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_object.setObjectName("Label_object")
        self.verticalLayout_10.addWidget(self.Label_object)
        self.verticalLayout_9.addWidget(self.frame)
        self.verticalLayout_2.addWidget(self.Splitter_sidePanel)
        self.horizontalLayout.addWidget(self.Splitter_frame)

        self.retranslateUi(MainPage)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(MainPage)

    def retranslateUi(self, MainPage):
        _translate = QtCore.QCoreApplication.translate
        MainPage.setWindowTitle(_translate("MainPage", "Form"))
        self.label_4.setText(_translate("MainPage", "Activated: "))
        self.label_active_None.setText(_translate("MainPage", "None"))
        self.label_active_HC.setText(_translate("MainPage", "Haar Cascade"))
        self.label_active_YOLO.setText(_translate("MainPage", "YOLO"))
        self.label_active_CM.setText(_translate("MainPage", "Custom Model"))
        self.image_label.setText(_translate("MainPage", "PRESS \"Start\" TO START WEBCAM"))
        self.Button_startCam.setText(_translate("MainPage", "Start"))
        self.label.setText(_translate("MainPage", "Frame Rate"))
        self.radioButton_showFrameRate.setText(_translate("MainPage", "Show frame rate"))
        self.label_3.setText(_translate("MainPage", "Resolution"))
        self.radioButton_res_0.setText(_translate("MainPage", "160 x 120 (4:3) "))
        self.radioButton_res_1.setText(_translate("MainPage", "320 x 240 (4:3)"))
        self.radioButton_res_2.setText(_translate("MainPage", "640 x 480 (4:3)"))
        self.radioButton_res_3.setText(_translate("MainPage", "800 x 600 (4:3) "))
        self.radioButton_res_4.setText(_translate("MainPage", "1280 x 720 (16:9)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_GeneralSettings), _translate("MainPage", "General Settings"))
        self.groupBox_HC_Cars.setTitle(_translate("MainPage", "Cars"))
        self.label_HC_Cars_ScaleFactor.setText(_translate("MainPage", "1"))
        self.label_10.setText(_translate("MainPage", "Scalefactor"))
        self.label_11.setText(_translate("MainPage", "Min neighbors"))
        self.label_HC_Cars_MinNeighbors.setText(_translate("MainPage", "1"))
        self.label_HC_Cars_MinSize.setText(_translate("MainPage", "0"))
        self.label_12.setText(_translate("MainPage", "Min size to detect"))
        self.Button_HC_Cars_Reset.setText(_translate("MainPage", "Reset"))
        self.groupBox_HC_LicencePlates.setTitle(_translate("MainPage", "Licence plates"))
        self.label_HC_LicencePlates_ScaleFactor.setText(_translate("MainPage", "1"))
        self.label_13.setText(_translate("MainPage", "Scalefactor"))
        self.label_14.setText(_translate("MainPage", "Min neighbors"))
        self.label_HC_LicencePlates_MinNeighbors.setText(_translate("MainPage", "1"))
        self.label_HC_LicencePlates_MinSize.setText(_translate("MainPage", "0"))
        self.label_15.setText(_translate("MainPage", "Min size to detect"))
        self.Button_HC_LicencePlates_Reset.setText(_translate("MainPage", "Reset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainPage", "Haar Cascade"))
        self.label_23.setText(_translate("MainPage", "Treshold"))
        self.label_YOLO_Treshold.setText(_translate("MainPage", "50"))
        self.Button_YOLO_Reset.setText(_translate("MainPage", "Reset"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainPage", "Yolo"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainPage", "Custom Model"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainPage", "Object Detection"))
        self.label_2.setText(_translate("MainPage", "Output"))
        self.Label_object.setText(_translate("MainPage", "Object"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainPage = QtWidgets.QWidget()
    ui = Ui_MainPage()
    ui.setupUi(MainPage)
    MainPage.show()
    sys.exit(app.exec_())
