# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(867, 587)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("*\n"
"{\n"
"    background-color: rgb(35, 35, 38);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"/* VERTICAL SCROLLBAR */\n"
"QScrollBar:vertical\n"
" {\n"
"     background-color: red;\n"
"     width: 15px;\n"
"     margin: 15px 3px 15px 3px;\n"
"     border: 1px transparent #2A2929;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"/*  HANDLE BAR VERTICAL */\n"
" QScrollBar::handle:vertical\n"
" {\n"
"     background-color: rgb(35, 35, 38);         /* Handle color */\n"
"     min-height: 5px;\n"
"     border-radius: 4px;\n"
" }\n"
"\n"
"QScrollBar::handle:vertical:hover{    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"QScrollBar::handle:vertical:pressed {    \n"
"    background-color: #0D0D0D;\n"
"}\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
" {\n"
"     background: none;\n"
" }\n"
"\n"
"/* Disable top and bottom arrows*/\n"
"QScrollBar::add-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"\n"
"/*Slider*/\n"
"\n"
"\n"
"/*\n"
"QSlider::groove:horizontal { \n"
"    background-color: black;\n"
"    border: 0px solid; \n"
"    height: 5px; \n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal { \n"
"    background-color: white; \n"
"    border: 2px solid; \n"
"    width: 10px; \n"
"    height: 20px; \n"
"    line-height: 20px; \n"
"    margin-top: -5px; \n"
"    margin-bottom: -5px; \n"
"    border-radius: 7px; \n"
"}\n"
"*/\n"
"\n"
"QSlider::groove:horizontal {\n"
"    background: white;\n"
"    height: 5px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1, stop: 0 #49BF88, stop: 1 #7289DA);\n"
"border: 0px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #eee, stop:1 #ccc);\n"
"border: 1px solid #777;\n"
"width: 13px;\n"
"margin-top: -5px;\n"
"margin-bottom: -5px;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 #fff, stop:1 #ddd);\n"
"border: 1px solid #444;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"background: #bbb;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"background: #eee;\n"
"border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"background: #eee;\n"
"border: 1px solid #aaa;\n"
"border-radius: 7px;\n"
"}\n"
"\n"
"\n"
"/*Buttons*/\n"
"\n"
"QPushButton{\n"
"    background-color: white;\n"
"    border-radius: 10;\n"
"}\n"
"\n"
"QPushButton:pressed {    \n"
"    background-color: #bcbcbc;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 22))
        self.menubar.setStyleSheet("/*QMenu*/\n"
"QMenu{\n"
"    background-color: rgb(51, 55, 61);\n"
"    color: white;\n"
"    selection-color: black;\n"
"    selection-background-color: #E4E4E5;\n"
"}\n"
"\n"
"QMenuBar::item{\n"
"    background-color: rgb(35, 35, 38);\n"
"    color: white;\n"
"}\n"
"\n"
"QMenuBar::item::selected {\n"
"    background-color: rgb(51, 55, 61);\n"
"}\n"
"\n"
"")
        self.menubar.setObjectName("menubar")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setAutoFillBackground(False)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuObject_detection = QtWidgets.QMenu(self.menubar)
        self.menuObject_detection.setObjectName("menuObject_detection")
        self.menu_HC = QtWidgets.QMenu(self.menuObject_detection)
        self.menu_HC.setObjectName("menu_HC")
        self.menu_CM = QtWidgets.QMenu(self.menuObject_detection)
        self.menu_CM.setObjectName("menu_CM")
        self.menu_CM_TF = QtWidgets.QMenu(self.menu_CM)
        self.menu_CM_TF.setObjectName("menu_CM_TF")
        self.menu_CM_TF_Lite = QtWidgets.QMenu(self.menu_CM)
        self.menu_CM_TF_Lite.setObjectName("menu_CM_TF_Lite")
        self.menu_YOLO = QtWidgets.QMenu(self.menuObject_detection)
        self.menu_YOLO.setObjectName("menu_YOLO")
        self.menuNavigation = QtWidgets.QMenu(self.menubar)
        self.menuNavigation.setTearOffEnabled(False)
        self.menuNavigation.setObjectName("menuNavigation")
        MainWindow.setMenuBar(self.menubar)
        self.actionView = QtWidgets.QAction(MainWindow)
        self.actionView.setObjectName("actionView")
        self.action_HowToUse = QtWidgets.QAction(MainWindow)
        self.action_HowToUse.setObjectName("action_HowToUse")
        self.action_About = QtWidgets.QAction(MainWindow)
        self.action_About.setObjectName("action_About")
        self.action_Camera = QtWidgets.QAction(MainWindow)
        self.action_Camera.setCheckable(True)
        self.action_Camera.setChecked(True)
        self.action_Camera.setObjectName("action_Camera")
        self.actionControls = QtWidgets.QAction(MainWindow)
        self.actionControls.setCheckable(True)
        self.actionControls.setChecked(True)
        self.actionControls.setObjectName("actionControls")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setCheckable(True)
        self.actionSettings.setChecked(True)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOutput = QtWidgets.QAction(MainWindow)
        self.actionOutput.setCheckable(True)
        self.actionOutput.setChecked(True)
        self.actionOutput.setObjectName("actionOutput")
        self.actionSettings_2 = QtWidgets.QAction(MainWindow)
        self.actionSettings_2.setObjectName("actionSettings_2")
        self.actionOutput_2 = QtWidgets.QAction(MainWindow)
        self.actionOutput_2.setObjectName("actionOutput_2")
        self.action_SidePanel = QtWidgets.QAction(MainWindow)
        self.action_SidePanel.setCheckable(True)
        self.action_SidePanel.setChecked(True)
        self.action_SidePanel.setObjectName("action_SidePanel")
        self.actionCar_detection = QtWidgets.QAction(MainWindow)
        self.actionCar_detection.setObjectName("actionCar_detection")
        self.action_Settings = QtWidgets.QAction(MainWindow)
        self.action_Settings.setCheckable(True)
        self.action_Settings.setChecked(True)
        self.action_Settings.setObjectName("action_Settings")
        self.action_Output = QtWidgets.QAction(MainWindow)
        self.action_Output.setCheckable(True)
        self.action_Output.setChecked(True)
        self.action_Output.setObjectName("action_Output")
        self.action_MainScreen = QtWidgets.QAction(MainWindow)
        self.action_MainScreen.setObjectName("action_MainScreen")
        self.action_Calibration = QtWidgets.QAction(MainWindow)
        self.action_Calibration.setObjectName("action_Calibration")
        self.action_HC_Cars = QtWidgets.QAction(MainWindow)
        self.action_HC_Cars.setCheckable(True)
        self.action_HC_Cars.setObjectName("action_HC_Cars")
        self.action_SSD = QtWidgets.QAction(MainWindow)
        self.action_SSD.setObjectName("action_SSD")
        self.action_HaarCascade_Licence_Plates = QtWidgets.QAction(MainWindow)
        self.action_HaarCascade_Licence_Plates.setCheckable(True)
        self.action_HaarCascade_Licence_Plates.setObjectName("action_HaarCascade_Licence_Plates")
        self.action_Full_Screen = QtWidgets.QAction(MainWindow)
        self.action_Full_Screen.setCheckable(True)
        self.action_Full_Screen.setObjectName("action_Full_Screen")
        self.action_CM_TF_Cars = QtWidgets.QAction(MainWindow)
        self.action_CM_TF_Cars.setCheckable(True)
        self.action_CM_TF_Cars.setObjectName("action_CM_TF_Cars")
        self.action_CM_TF_Cars_etc = QtWidgets.QAction(MainWindow)
        self.action_CM_TF_Cars_etc.setCheckable(True)
        self.action_CM_TF_Cars_etc.setObjectName("action_CM_TF_Cars_etc")
        self.action_CM_TF_Lite_Cars = QtWidgets.QAction(MainWindow)
        self.action_CM_TF_Lite_Cars.setCheckable(True)
        self.action_CM_TF_Lite_Cars.setObjectName("action_CM_TF_Lite_Cars")
        self.action_CM_TF_Lite_Cars_etc = QtWidgets.QAction(MainWindow)
        self.action_CM_TF_Lite_Cars_etc.setCheckable(True)
        self.action_CM_TF_Lite_Cars_etc.setObjectName("action_CM_TF_Lite_Cars_etc")
        self.action_YOLO_80_objects = QtWidgets.QAction(MainWindow)
        self.action_YOLO_80_objects.setCheckable(True)
        self.action_YOLO_80_objects.setObjectName("action_YOLO_80_objects")
        self.menuView.addAction(self.action_Camera)
        self.menuView.addAction(self.action_SidePanel)
        self.menuView.addAction(self.action_Settings)
        self.menuView.addAction(self.action_Output)
        self.menuView.addAction(self.action_Full_Screen)
        self.menuHelp.addAction(self.action_HowToUse)
        self.menuHelp.addAction(self.action_About)
        self.menuHelp.addSeparator()
        self.menu_HC.addAction(self.action_HC_Cars)
        self.menu_CM_TF.addAction(self.action_CM_TF_Cars)
        self.menu_CM_TF.addAction(self.action_CM_TF_Cars_etc)
        self.menu_CM_TF_Lite.addAction(self.action_CM_TF_Lite_Cars)
        self.menu_CM_TF_Lite.addAction(self.action_CM_TF_Lite_Cars_etc)
        self.menu_CM.addAction(self.menu_CM_TF.menuAction())
        self.menu_CM.addAction(self.menu_CM_TF_Lite.menuAction())
        self.menu_YOLO.addAction(self.action_YOLO_80_objects)
        self.menuObject_detection.addAction(self.menu_HC.menuAction())
        self.menuObject_detection.addAction(self.menu_YOLO.menuAction())
        self.menuObject_detection.addAction(self.menu_CM.menuAction())
        self.menuNavigation.addAction(self.action_MainScreen)
        self.menuNavigation.addAction(self.action_Calibration)
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuNavigation.menuAction())
        self.menubar.addAction(self.menuObject_detection.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuObject_detection.setTitle(_translate("MainWindow", "Object Detection"))
        self.menu_HC.setTitle(_translate("MainWindow", "Haar Cascade"))
        self.menu_CM.setTitle(_translate("MainWindow", "Custom Model"))
        self.menu_CM_TF.setTitle(_translate("MainWindow", "Tensorflow"))
        self.menu_CM_TF_Lite.setTitle(_translate("MainWindow", "Tensorflow Lite"))
        self.menu_YOLO.setTitle(_translate("MainWindow", "YOLO"))
        self.menuNavigation.setTitle(_translate("MainWindow", "Navigation"))
        self.actionView.setText(_translate("MainWindow", "View"))
        self.action_HowToUse.setText(_translate("MainWindow", "How to use"))
        self.action_About.setText(_translate("MainWindow", "About"))
        self.action_Camera.setText(_translate("MainWindow", "Camera"))
        self.actionControls.setText(_translate("MainWindow", "Controls"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))
        self.actionOutput.setText(_translate("MainWindow", "Output"))
        self.actionSettings_2.setText(_translate("MainWindow", "Settings"))
        self.actionOutput_2.setText(_translate("MainWindow", "Output"))
        self.action_SidePanel.setText(_translate("MainWindow", "Side panel"))
        self.actionCar_detection.setText(_translate("MainWindow", "TensorFlow"))
        self.action_Settings.setText(_translate("MainWindow", "Settings"))
        self.action_Output.setText(_translate("MainWindow", "Output"))
        self.action_MainScreen.setText(_translate("MainWindow", "Main"))
        self.action_Calibration.setText(_translate("MainWindow", "Calibration"))
        self.action_HC_Cars.setText(_translate("MainWindow", "Cars"))
        self.action_SSD.setText(_translate("MainWindow", "SSD"))
        self.action_HaarCascade_Licence_Plates.setText(_translate("MainWindow", "Licence Plates"))
        self.action_Full_Screen.setText(_translate("MainWindow", "Full Screen"))
        self.action_CM_TF_Cars.setText(_translate("MainWindow", "Cars"))
        self.action_CM_TF_Cars_etc.setText(_translate("MainWindow", "Cars, signs and lampposts"))
        self.action_CM_TF_Lite_Cars.setText(_translate("MainWindow", "Cars"))
        self.action_CM_TF_Lite_Cars_etc.setText(_translate("MainWindow", "Cars, signs and lampposts"))
        self.action_YOLO_80_objects.setText(_translate("MainWindow", "80 different objects"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
